### ISSUE TITLE
this.buildCountSOQL() method error

### ISSUE THREAD

**Issue by Sourabh42** [Sarveshgithub/sfdc-lwc-lightning-datatable#1]
In Javascript file the countsoql method is called  which passes this.buildCountSOQl method as a parameter but this method is not availabel in js file. so can u helpme to find the method

**Comment by Sarveshgithub** [comment]
@Sourabh42, Issue has been resolved.

**Comment by Sourabh42** [comment]
yaa it works now, Thanks
