### ISSUE TITLE
enhancement : Pagination with the (current number of page / total number)

### ISSUE THREAD

**Issue by mickaelgudin** [Sarveshgithub/sfdc-lwc-lightning-datatable#109]
The idea is consistent with what most website do when they have a pagination and it's more user friendly.

This should be place at the center on the same row as pagination buttons and should be enabled only if pagination is enabled.

**Comment by Sarveshgithub** [comment]
@mickaelgudin Yhea this is a good enhancement for UI, One thing is this also allows page numbers with redirection link 
here is a sample of [design](https://fireart.studio/blog/pagination-design-examples/), lots of [design](https://dribbble.com/tags/pagination). We have to choose UI somewhat math with SF UI.

**Comment by anupkage** [comment]
can we build like this ?
will follow slds standard design for styling 
<img width="692" alt="image" src="https://user-images.githubusercontent.com/21004994/190450419-ad4a58f4-600c-48eb-b8b1-9fcd7425c740.png">

reference: https://github.com/carbon-design-system/carbon/issues/2634

**Comment by anupkage** [comment]
<img width="306" alt="image" src="https://user-images.githubusercontent.com/21004994/190451287-648e3ff2-2058-411d-b2a5-63e597efee9e.png">

reference: https://github.com/carbon-design-system/carbon/issues/2634

**Comment by Sarveshgithub** [comment]
@anupkage yhea design looks amazing, be include the first/last button as well. can I assign this to you?

**Comment by anupkage** [comment]
Yes you can assign it to me

**Comment by anupkage** [comment]
@Sarveshgithub Do we need to implement dropdown ?

**Comment by Sarveshgithub** [comment]
@anupkage dropdown is too much let's keep simple first design is fine https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/issues/109#issuecomment-1248295216.  

one more thing - not sure `...` this logic seems a bit challenging to me. depends on you if want to show all indexes or with limited indexes with `...`, I would suggest showing all index to keep simple but depends on you

**Comment by Sarveshgithub** [comment]
Hey, @anupkage please add your GitHub email to the local machine, so that your GitHub account shows in the contribution section. check this [article](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile)

**Comment by anupkage** [comment]
I have implemented this type of pagination earlier
I will try to complete it By tomorrow 18  September and to ready for code review

**Comment by Sarveshgithub** [comment]
hey, @anupkage just wanted to check on this.

**Comment by anupkage** [comment]
Hey i have implemented pagination but struck with one bug.
Will discuss that tomorrow morning i will ping you.
