### ISSUE TITLE
Buttons of list should be configurable

### ISSUE THREAD

**Issue by mickaelgudin** [Sarveshgithub/sfdc-lwc-lightning-datatable#11]
This feature would be useful if the component is a child of another component and the parent needs to listen to the fired events.

**Description of the implementation of the new prop "list action button" and events :**
- a custom event would be fired it'd be name  : "action"+((index in actions array)+1)
- a button label for each button
- a variant name for each button
- a new boolean prop to allow the user to show checkboxes and to get selected rows (using prop selected-rows and onrowselection of the component lightning-datatable)

Json would be :

```
[  
   {  label : "delete all", variant: "destructive", needSelectedRows: true },
   { label : "another action button", variant : "brand", needSelectedRows: false }
]
```

Here's the label of the button from the json and their action names
"delete all" : action1
"another action button" : action2

Selected rows would be send to the event only if the button has needSelectedRows property set to true

**Comment by Sarveshgithub** [comment]
@mickaelgudin thanks again for the new addon, I do have some queries, 
- what happens if the component has no parent. then in that case event was fired? 
- are you firing events only if the component has a parent?

**Comment by mickaelgudin** [comment]
prop "list action button" :  

- set to null by default
- if the prop is not null (and it's consistent with the above json) then the buttons would be displayed and the related events would be fired

But I think you're making a point, this addon should allow apex calls from the component itself
```
[  
   {  label : "delete all", variant: "destructive", needSelectedIds: true, callApex: true },
   { label : "another action button", variant : "brand", needSelectedIds: false, callApex: false }
]
```
Therefore two methods would be defined in javascript controller (called based on callApex value) : 
- fireEventFromButton (if callApex is false)
- callApexFromButton (if callApex is true)

I think it's the best solution, because a centralised apex method(for buttons that want to call apex method directly without firing event to parent) might not meet all uses cases.

**The callApexFromButton method would enable developers to add custom logic(call desired apex method) based on labels.**

**Comment by Sarveshgithub** [comment]
@mickaelgudin Just check i believe `actionButtonsList` property was missed in metafile for design attribute. can you add this property to the design attribute? and update the config table in read.me section

**Comment by mickaelgudin** [comment]
I'll rename callApex to callListAction

**You're making a point for buttons with logic defined in related list component :** 

I think the best way is to separate buttons : 
- the ones with logic defined in related list (actionButtonsList)
- the ones just throwing an event (eventButtonsList )

actionButtonsList would be configure that way depending on the logic (event, action defined in relatedList apex/javascript) : 
```
{
"button-delete-all" : {  label : "delete all", variant: "destructive", needSelectedRows: true, callListAction: true }
"another-button" : {  label : "another list button", variant: "destructive", needSelectedRows: true, callListAction: true }
}
```
The design property (a String) for actionButtonsList would reference buttons that way : 
`button-delete-all, another-button`

eventButtonsList would be configured from parent component just as before : 
```
[  
   {  label : "delete all", variant: "destructive", needSelectedRows: true, callListAction: true },
   { label : "another action button", variant : "brand", needSelectedRows: false, callListAction: false }
]
```

I'm okay with this rule `if actionButtonsList != null , set showcheckbox = true`

**Comment by mickaelgudin** [comment]
I'm okay with defining only actions for list for the time being, you could make a release after that.

Your future features are great, I'm not sure about 4. though, there is this repo for this use case : https://github.com/seanpat09/dynamicFieldsLWC

**Comment by Sarveshgithub** [comment]
@mickaelgudin  I have published a new Release with all recent changes. v1.2

**Comment by mickaelgudin** [comment]
thank you, I think we can close this issue since the provided changes should be suited for admins and developers.
