### ISSUE TITLE
enhancement : custom labels as an option for title and button labels

### ISSUE THREAD

**Issue by mickaelgudin** [Sarveshgithub/sfdc-lwc-lightning-datatable#110]
The idea of #108 might be could(as an option) for : 

- the title
- the pagination buttons
- view all / collapse buttons

**Comment by Sarveshgithub** [comment]
@mickaelgudin Ahh that's too much configuration because the title can be customized from Design Attribute, action buttons can also provide from Design Attribute, and Button Label should be the same, for view all/collapse we have icon

**Comment by mickaelgudin** [comment]
ok fair enough
