### ISSUE TITLE
enhancement : Search results with pagination disabled

### ISSUE THREAD

**Issue by mickaelgudin** [Sarveshgithub/sfdc-lwc-lightning-datatable#119]
**feature :** Search with pagination enabled

**What I have tested :** Search then click on button "previous" or "next" or "first" or "last"

**Input :** Input with result in next page or in previous page

**Result :**  When we click on "Next" or "Previous" the offset before the search is still active.

**Proposed enhancement :**

- if there is a search term then the pagination buttons are disabled(because all search results are displayed on search(there is no limit in the SOSL query) and I believe it should remain that way)
- replace the type of the lightning-input (it should be type="search" not "text", because the search type provides a search icon + a cross to remove entry)

_Originally posted by @mickaelgudin in https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/discussions/71#discussioncomment-3656999_

**Comment by Sarveshgithub** [comment]
@mickaelgudin Good finding, I will take a look

**Comment by Sarveshgithub** [comment]
Fixed PR https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/pull/128
