### ISSUE TITLE
bug : Search results sorting ignores search term

### ISSUE THREAD

**Issue by mickaelgudin** [Sarveshgithub/sfdc-lwc-lightning-datatable#120]
The sort action fetch records and ignores the search term,

if there is a search term : sort should be made on search results only

**Comment by Sarveshgithub** [comment]
we will disable sort on search, because we need to add the where clause on all fields with the searchterm, i don't want to complicate the things, so disabling sort is good option

**Comment by Sarveshgithub** [comment]
Fixed PR https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/pull/128
