### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by Sarveshgithub** [Sarveshgithub/sfdc-lwc-lightning-datatable#121]
# Filter - new feature on the data table

- This feature works the same as list view filters, but we have to create a custom solution
- Users can create filters and save them, easy to choose and display record sets
- Users can edit, delete, rename, private/public filters

### Schema
- **Filter** ( custom Object ) 
- **Fields**: Condition (textarea, Store conditions i.e `Name = 'test'` ), Public ( Boolean ), Screen ( Text, store api name of component easily to identify, need to required design attribute called `Name` )

## UI
- Picklist -  to show filters based ( private at the top, then public filters ) - placed left to the Search
- Button Icon ( edit/delete ) - right to above picklist
- Edit - on edit click modal popup open with filter UI
- Delete - warning delete, sure/cancel
- Filter UI - Find out( GitHub/google search ) this component and grab it, otherwise, we have to build  ![image](https://user-images.githubusercontent.com/40709233/190562578-bddd0989-c272-49f0-b0f4-49cdd78c645e.png)

## Impact
- maybe on search

## Action
- Find out filter component - main action

**Comment by Sarveshgithub** [comment]
@mickaelgudin , @anup ( why you not coming, ahh you need to wait for 24h  😩 to add to contribution)

can you guys take a look, Feel free to add on the Impact side, can you guys search the filter component  below mention point
`UI Find out( GitHub/google search ) this component and grab it, otherwise, we have to build`

**Comment by mickaelgudin** [comment]
I didn't find much, only something that was implemented in aura component : 

- https://www.greytrix.com/blogs/salesforce/2021/08/17/how-to-create-a-dynamic-multi-filter-object-in-salesforce-part-i/
- https://www.greytrix.com/blogs/salesforce/2021/08/18/how-to-create-a-dynamic-multi-filter-object-in-salesforce-part-ii/

**Comment by Sarveshgithub** [comment]
@mickaelgudin Yhea that good finding, will be created from start, at least will utilize Apex, I just started basic, just created Object. branch is `listFilter`

**Comment by Sarveshgithub** [comment]
added list template placeholder commit: https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/commit/52b950102ebd768c77e91b6580897d43e24c955c
