### ISSUE TITLE
Add master label and svg icon

### ISSUE THREAD

**Issue by anupkage** [Sarveshgithub/sfdc-lwc-lightning-datatable#122]
Master label will help admin and developers to find the component very easily in page builder. 
component name **lwcRelatedList** is confusing for dynamic data table.

**Comment by Sarveshgithub** [comment]
@anupkage yhea good suggestion

Label = `sfdc-lwc-lightning-datatable`
Icon = choose from [here](https://www.lightningdesignsystem.com/icons/). choose icon that looks catchy 😁
Help doc how to do [this](https://rajendrasnagar.wordpress.com/2020/12/22/add-svg-icon-to-your-lwc-component/)

@mickaelgudin can you take a look on it

**Comment by mickaelgudin** [comment]
@Sarveshgithub  this one looks great and it's consistent with that the component provides

![image](https://user-images.githubusercontent.com/39730173/190854182-f3f4f280-0255-4453-85d1-20e35df496fa.png)
