### ISSUE TITLE
[ BUG ] - When a date is edited time input is displayed

### ISSUE THREAD

**Issue by mickaelgudin** [Sarveshgithub/sfdc-lwc-lightning-datatable#143]
**Describe the bug**
When a column is declared as date(the field is of type date) the time input is displayed

![image](https://user-images.githubusercontent.com/39730173/193649071-27106b65-f99f-4514-b775-310d988cdd48.png)

**To Reproduce**
1. Select Birthdate for the component
2. Edit the Birthdate on one contact the time input gets displayed (see the figure above)

**Expected behavior**
Only one input should be displayed

![image](https://user-images.githubusercontent.com/39730173/193649422-09c01b87-430b-44d0-8e5d-87a39bf9643a.png)

**Comment by mickaelgudin** [comment]
@Sarveshgithub I'm on it, I'll do a PR,

when type = 'date ' : json type = 'date-local'

It works that way

![image](https://user-images.githubusercontent.com/39730173/193649693-d30dfe2a-65d7-4bfc-8287-7a8e16b85e2e.png)

**Comment by Sarveshgithub** [comment]
@mickaelgudin 👍
