### ISSUE TITLE
[ BUG ] - When a user specifies the Id the component has an error

### ISSUE THREAD

**Issue by mickaelgudin** [Sarveshgithub/sfdc-lwc-lightning-datatable#152]
**Describe the bug**
When we set Id field in the prop api names there is an error (because the Id field is already retrieved by defautl)

**Expected behavior**

update documentation to specify not to include Id in columns since retrieved by default (otherwise users will get this error not knowing why).

**Comment by Sarveshgithub** [comment]
fixed @mickaelgudin can you test

**Comment by mickaelgudin** [comment]
The idea is great, I thought of it right after reporting this issue, you did great @Sarveshgithub.


However, they were issues :
- the join function didn't exist (it throws an error, we have to convert the Set into an Array)
- the case "iD" wasn't taken into account (we have to take it into account even if it is a weird input, better safe than sorry :)  )


Here's the correction I made, I tested every scenario(only one field, every Id cases), it works great
```
    //remove id field if set
    let tempFields = new Set(cmp.fields.replace(/\s/g, '').split(','));
    ['id', 'Id', 'iD', 'ID'].forEach(idFieldCase => {
        if (tempFields.has(idFieldCase)) {
            tempFields.delete(idFieldCase);
        }
    });
    cmp.fields = tempFields.join(',');
```
