### ISSUE TITLE
[ Enhancement ] - Edit picklist field

### ISSUE THREAD

**Issue by mickaelgudin** [Sarveshgithub/sfdc-lwc-lightning-datatable#164]
We can add custom type to the generic datatable,

here the idea is to allow edition of picklist field 

I found an existing approach : https://upsource.solutions/blog/69-adding-a-picklist-to-the-lightning-datatable.html

**Comment by Sarveshgithub** [comment]
@mickaelgudin hmm let me brainstorm on this impact wise

**Comment by mickaelgudin** [comment]
no impact,

we can extend lightning:datatable and add another datatype, existing features will not be impacted you check my dev branch I started the implementation.
