### ISSUE TITLE
[ Enhancement ] -  Lookup as custom datatype

### ISSUE THREAD

**Issue by mickaelgudin** [Sarveshgithub/sfdc-lwc-lightning-datatable#167]
It appears to be possible : https://github.com/jangidyogi94/SFDC-Recipes/tree/Lookup-in-Lightning-Datatable/src/lwc

I think I will implement it before the promotion of the repo since it's often needed.

Can you assign me this issue?

**Comment by Sarveshgithub** [comment]
that's a good enhancement

**Comment by Sarveshgithub** [comment]
Hey, @mickaelgudin Wish you a Happy new year. any luck on this enhancement

**Comment by mickaelgudin** [comment]
Hey @Sarveshgithub, happy new year !

I started an implementation for this enhancement, 
I hope it'll be done by the end of this month

**Comment by mickaelgudin** [comment]
@Sarveshgithub Almost done, 

I fixed an issue that I found while testing : custom datatypes draft values were not merge with draft values of standard types.


The only remaining issue is that when the focus is lost(we click on another cell)
The lookup or the picklist should come back to normal cell display style.

**Comment by Sarveshgithub** [comment]
Hey @mickaelgudin  I have tested some scenarios - found some issues
**Input Data**
**Object** - Contact
**Cols** - FirstName,Account.Name,LastName,Level__c,CreatedDate
**Customized col JSON** - {     "Account.Name":     {         "label":"Account Name",    "editable":true,     "type":"lookup",         "typeAttributes":{             "placeholder": "Choose Account",             "objectApiName": "Contact",             "fieldName": "AccountId",             "label": "Account",             "value": { "fieldName": "AccountId" },             "context": { "fieldName": "Id" },             "variant": "label-hidden",             "name": "Account",             "fields": ["Account.Name"],             "target": "_self"         }      }  } 

**Note : Level__c is picklist**


1. I have added `"editable":true` on col customized json to enable the standard edit icon it shows two icons( lookup custom icon and datatable icon ), can we utilize standard icon, on click of edit fire event to enable lookup.
<img width="948" alt="image" src="https://user-images.githubusercontent.com/40709233/215509896-fb103043-b22d-43cf-af97-75121ea76a5d.png">

2. save functionality not working `onlookupchanged` event not enabling save and cancel button, below code not working : might be column api names
` //show standard cancel & save button
        copyDraftValues.forEach((item) => {
            if (item.Id === updateItem.Id) {
                item[fieldName] = updateItem[fieldName];

                draftValueChanged = true;
            }
        });`
3. Edit picklist field is also not enabling save and cancel, the above same issue
4. First i edit lookup field then i tried to edit picklist field, but i can't select picklist values from dropdown, might be focus event issue. not sure if same issue for you

**Comment by mickaelgudin** [comment]
I'll have a lookup but for **1.** both lookup and picklist custom datatype have to include the icon within the "custom cell" so we can't use "editable": true

**Comment by Sarveshgithub** [comment]
thanks @mickaelgudin  changes you made solve the above issue 
1. is it possible to show the edit icon on an empty lookup field and update?
<img width="955" alt="image" src="https://user-images.githubusercontent.com/40709233/216102122-12e61e7c-1a0f-4245-b01f-735a06e20429.png">

**Comment by Sarveshgithub** [comment]
hmm ok let me see
