### ISSUE TITLE
[ Enhancement ] -  Multipicklist as custom datatype

### ISSUE THREAD

**Issue by mickaelgudin** [Sarveshgithub/sfdc-lwc-lightning-datatable#168]
@Sarveshgithub The standard behavior of list views and related list are not to display a picklist if we edit a field "multipicklist" but this :
![image](https://user-images.githubusercontent.com/39730173/199625393-97ba7536-4dfa-42e8-8306-bc320e97cd3a.png)

This issue is not a priority (since the standard behavior is not user friendly since you have to stay on the "ctrl" key when selecting items, so I doubt that the inline edition of multipicklist field is common)

**Comment by Sarveshgithub** [comment]
@mickaelgudin hmm let's stics with a single picklist. people don't often use multiple picklists now days.

**Comment by mickaelgudin** [comment]
@Sarveshgithub can you tag this issue as : wontimplement (with a new label)
