### ISSUE TITLE
[ BUG ] - lwcRelatedList error when component is added through app builder

### ISSUE THREAD

**Issue by mickaelgudin** [Sarveshgithub/sfdc-lwc-lightning-datatable#184]
**Describe the bug**

**Where :** lwcRelatedList.js 

replace the code
```
import LightningDatatable from 'lightning/datatable';

export default class LwcDatatable extends NavigationMixin(
    LightningElement(LightningDatatable)
) {
```

to

`export default class LwcDatatable extends NavigationMixin(
    LightningElement
) {`

**Why :** It leads to bug in App builder, invalid, and the lwcRelatedList is not the component used to extends lightning:datatable features(which is done by extendedDatatable).

@Sarveshgithub could you have a look. It's a quick fix?

**Comment by Sarveshgithub** [comment]
resolved
