### ISSUE TITLE
[ Enhancement ] -  New button : allow record type selection

### ISSUE THREAD

**Issue by mickaelgudin** [Sarveshgithub/sfdc-lwc-lightning-datatable#186]
It appears to be possible using state in props : https://salesforce.stackexchange.com/questions/254498/lightning-web-components-navigate-to-the-new-object-page-passing-in-specific 

```
this[NavigationMixin.Navigate]({
      type: 'standard__objectPage',
      attributes: {
        objectApiName: 'Account',
        actionName: 'new'
      },
      state: {
        useRecordTypeCheck: 1
      }
    });
```
**where :** lwcRelatedList.js, the method newRecord

Could you have a look @Sarveshgithub

**Comment by Sarveshgithub** [comment]
done
