### ISSUE TITLE
cant work on dynamic query

### ISSUE THREAD

**Issue by Sourabh42** [Sarveshgithub/sfdc-lwc-lightning-datatable#2]
when i deploy the compoenent on specific object record page then the query executed after where condition should not include the current record page data. it should exclude it.

**Comment by Sarveshgithub** [comment]
@Sourabh42  could you please provide, **Column JSON** and **Where Clause** Values that you are adding to the design attribute, this might be helpful to find the culprit. Thanks!

**Comment by Sourabh42** [comment]
suppose I deploy the component on the contact Record Page. and the record contains FirstName=' Sourabh'  so this query 
select Id, FirstName, Phone from Contact where Name=' Sourabh' should not include current record. it should display the record except this record. so can u tell me the changes in query.

**Comment by Sourabh42** [comment]
i apply the console in js file but cant seen any console on console log

**Comment by Sarveshgithub** [comment]
@Sourabh42 Read the **Read.me** Instruction will help you how to configure the component.
As you mention  FirstName=' Sourabh', for this you need to provide FirstName=' Sourabh' in Where Clause Field while adding component into Flexipage. 

![image](https://user-images.githubusercontent.com/40709233/97996424-c39a2780-1e0d-11eb-99e4-c8b2b55eb5ce.png)

**Comment by Sourabh42** [comment]
can u suggest the functionality in where clause which will able to skip the current record according to record Id

**Comment by Sarveshgithub** [comment]
@Sourabh42 , you can update the .js code, by adding default where condition in SOQL i.e : WHERE Id = recordID
