### ISSUE TITLE
[ BUG ] - When a record is deleted update the counter

### ISSUE THREAD

**Issue by mickaelgudin** [Sarveshgithub/sfdc-lwc-lightning-datatable#206]
**Describe the bug**
When we delete a record the counter of record isn't updated

**To Reproduce**

- Configure the component to show the number of record
- Delete a record
- You'll see that the counter isn't updated

**Expected behavior**

When a record has been successfully deleted we have to call the method to update the counter of records.

**Comment by Sarveshgithub** [comment]
fixed
