### ISSUE TITLE
[ Enhancement ] -  Improve performance and load test 

### ISSUE THREAD

**Issue by Sarveshgithub** [Sarveshgithub/sfdc-lwc-lightning-datatable#209]
1. Optimized LWC
2. Optimized Apex
3. Change the pattern for data fetching?

**Comment by mickaelgudin** [comment]
@Sarveshgithub Lazy load is the way to go just like in standard list views.

**Conditions**

- **if** the limit clause is not specfied **OR** pagination is not enabled
**then** use lazy load (for each load we retrieve 50 rows : based on standard list view behaviour)
- **if**  the new prop "disable lazy loading" is checked
**then** fetch data at once (for uses cases where we want to show all records and the number of records is higher than 50)

**Comment by Sarveshgithub** [comment]
> @Sarveshgithub Lazy load is the way to go just like in standard list views.
> 
> **Conditions**
> 
> **Lazy loading & Pagination**
> 
> * **if** the limit clause is not specfied **OR** pagination is not enabled
>   **then** use lazy load (for each load we retrieve 50 rows : based on standard list view behaviour)
> * **else**
>   load data with the specified limit
> 
> **Lazy loading should be an option (checked by default)**
> 
> * **if**  the new prop "disable lazy loading" is checked
>   **then** fetch data at once (for uses cases where we want to show all records and the number of records is higher than 50)

yhea Lazy loading is one of good option

**Comment by Sarveshgithub** [comment]
improved some Apex performance and optimized code
