### ISSUE TITLE
[ ENHANCEMENT ] - When a picklist field is not defined in custom json the picklist values are not retrieved

### ISSUE THREAD

**Issue by mickaelgudin** [Sarveshgithub/sfdc-lwc-lightning-datatable#219]
**To Reproduce**
Select the StageName for Opportunity, you'll see that you picklist values are not retrieved is you don't define a custom json.

**Expected behavior**
Retrieve the picklist values as it is the case when we define the picklist field in the custom

The fix is easy, I'll do a PR

**Comment by Sarveshgithub** [comment]
hey @mickaelgudin but picklist is mandatory to defined in custom json write [this readme](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable#picklist-editable-column:~:text=Name%22%2C%20%22type%22%3A%20%22text%22%20%7D%20%7D-,Picklist%20editable%20column,-%7B%22StageName%22%20%3A%20%7B%22type%22%3A%20%22picklist)

**Comment by mickaelgudin** [comment]
@Sarveshgithub my bad I should have report this as enhancement

I tested my change it works fine

**Comment by mickaelgudin** [comment]
@Sarveshgithub All good.
