### ISSUE TITLE
Columns declaration format : declare columns using SELECT clause

### ISSUE THREAD

**Issue by mickaelgudin** [Sarveshgithub/sfdc-lwc-lightning-datatable#23]
In order to make the component easier to configure, we should allow a SELECT-like format for columns declaration, 
it would also be consistent with existing properties that are represent elements of an SOQL statement(object name, where, limit...)

Ideas for the implementation : 

**Two options(either one or two properties)** : 
- SELECT-like format
- lightning-datatable JSON format (the current option)

It would require to translate SELECT-like input to a lightning-datatable JSON format to configure the columns of the component lightning-datatable, it requires retriving the labels of all the fields

**Comment by Sarveshgithub** [comment]
@mickaelgudin are you talking about Like operators in SOQL. if so, then it could be added in as a where clause via design attribute. ex: `Name like %John%`. Table columns and SOQL  are prepared via JSON.

**Comment by mickaelgudin** [comment]
@Sarveshgithub no I'm talking about the way we define columns.

Currently we are required to use this format : 
```
[
     { "fieldName": "FirstName",
        "label": "First Name",
        "type": "text"
    }, {
        "fieldName": "LastName",
        "label": "Last Name",
        "type": "text"
    }
]
```

This new add-on would **allow declaration of columns using SELECT clause format**, 
which for the above example would be : `FirstName, LastName`

**the above json would be created based on fields properties**(type, and label)

**Comment by Sarveshgithub** [comment]
@mickaelgudin yhea Basically Fields API Name can enter with comma-separated via design attribute. This change can impact the whole design. we need to change the whole logic. Initially, this idea has in my mind. but I have chosen JSON structure. This can be a good candidate for Optimization. will do this later, currently focusing on new addon features.

**Comment by mickaelgudin** [comment]
I tested your implementation it's great, the json definition was way too heavy; however, I believe the following issues should be addressed :


in the apex class

**1. Display field of relation** (we can't display Account.Name of Contact for example)

We could have a prop to define the related fields json because I don't think we can retrieve related fields infos (ex : Account.Name, in apex we can't have the description of this field...)

***The new prop is only a suggestion, if you find a way to retrieve fields description of an object relationship it could be great and more clean***

**2. Error in the counter when a limit is defined**

the method buildFieldJson should include the limit (new parameter) and the whereclause passed to the method countRecords should include the limit

**3. Display formatted date**

`SELECT FORMAT(CreatedDate) FROM Account //currently we can't display this`

- a regex should be enough to get only the field names(format can be used on several fields) in that case
- the type should be text in that case

**(optional) 4. code formatting**
- rename accountType to objectType

**Comment by Sarveshgithub** [comment]
@mickaelgudin how are you doing man 😁
1. Yes Related Fields can't show in the table, Need to add some solution in Apex, i.e It will Describe up to the topmost child ( Like Account.Opportunity.Name, so in that case column name should be Opportunity Name). I have to build this solution.
2. I can see count records with no error, count should show all records. if we add a limit then it will show only a certain count
3. Yes, there is an issue with DataType. because Field Datatype are not the same as LWC data, To fix this, need to create a map of field data type to lwc data type. Ex :  map<string, string>{Datetime, Date}
4. not able to find `accountType`, where it is

**Comment by mickaelgudin** [comment]
@Sarveshgithub I believe we should reopen the issue, here's a detail for each point :

1. Ok, sounds great

2. Okay, so I checked the code and the issue is that limit could be used without pagination(example : 3 most recent opportunities with criterias in the where), so we should include a case where : 

```
if(hasPagination == false && limit > 0) {
counter = number of records retrieved with the limit
}
```

3. Yes a mapping of type could be great,
My point was that the select can include : format(field) or count(field)
We should use regex when iterating on fieldname in the apex method buildFieldJSON to isolate fields name to get their description

4. at line 46 and 47 in the apex class

**Comment by Sarveshgithub** [comment]
@mickaelgudin 
2. the functionality of count is that it displays all count() records in the system.  If there is a where filter then counts Query appends with where clause.

check the local config
pagination = false and limit = 5
![image](https://user-images.githubusercontent.com/40709233/185427407-d828cb15-43db-41ef-9e67-40fa9fbfff71.png)

Result are showing fine
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/40709233/185427611-2b2cb456-6f64-4ef4-ad2f-49c0143714a9.png">
