### ISSUE TITLE
[ Feature ] - allow SOQL functions and aliases

### ISSUE THREAD

**Issue by mickaelgudin** [Sarveshgithub/sfdc-lwc-lightning-datatable#252]
The idea is to allow users to use COUNT(), min, max... functions and aliases.

**Functions**

https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_functions.htm

<br><br>

@Sarveshgithub Can you assign me this issue?

**Comment by Sarveshgithub** [comment]
@mickaelgudin hope you are doing, just wanted to follow up on this

**Comment by mickaelgudin** [comment]
@Sarveshgithub yeah, I'm still planning on implementing this feature, I'm currently moving out so I don't have much time but I believe I will implement this before the end of this year. I'll let you know.
