### ISSUE TITLE
prod deployment issue

### ISSUE THREAD

**Issue by Sarveshgithub** [Sarveshgithub/sfdc-lwc-lightning-datatable#260]
Hi @Sarveshgithub ,

Everything works well in sandbox but when I tried to deploy to Production, I get an error on the APEX Test Classe : 

Deployment CompleteTest failure, method: RelatedList_Test.buildFieldJSON_Test -- System.AuraHandledException: Script-thrown exception stack Class.RelatedList.buildFieldJSON: line 183, column 1
Class.RelatedList_Test.buildFieldJSON_Test: line 19, column 1

Could you please help me to fix this issue?

Thank you,

_Originally posted by @RemyGenius in https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/discussions/71#discussioncomment-7755894_

**Comment by Sarveshgithub** [comment]
@RemyGenius  can you please include steps and error screenshot please

**Comment by RemyGenius** [comment]
Yes ! 
<img width="1512" alt="Capture d’écran 2023-12-04 à 19 04 01" src="https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/assets/127290269/5be722ed-bbb2-4b67-87ea-8bedde18f31f">
<img width="1512" alt="Capture d’écran 2023-12-04 à 19 04 55" src="https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/assets/127290269/12781745-4718-4ec5-b8ff-3344c961b271">
<img width="1512" alt="Capture d’écran 2023-12-04 à 19 06 16" src="https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/assets/127290269/f8d3e433-3628-4b1e-915f-a524ee4df3b4">

**Comment by mickaelgudin** [comment]
@Sarveshgithub it would appears that the field(Contact.Level__c) is not recognised since it doesn't exist

We just need to remove this part :

![image](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/assets/39730173/0ace8ee4-c499-4369-b74e-c948bac9685e)

**Comment by Sarveshgithub** [comment]
https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/pull/261/commits/b923ae190ba448c5d538394726ecba2250b78f43

**Comment by Sarveshgithub** [comment]
@mickaelgudin yhea thanks for pin point, @RemyGenius i have resolved this issue, let us know if you still facing same, thanks!

**Comment by RemyGenius** [comment]
Everything works thanks!
