### ISSUE TITLE
[ Enhancement ] -  Have the ability to specify recordId and connectedUserId

### ISSUE THREAD

**Issue by mickaelgudin** [Sarveshgithub/sfdc-lwc-lightning-datatable#263]
the idea is simple in the where clause : 

`WHERE AccountId <> {recordId} `

`WHERE CreatedById = {connectedUserId} `

we replace {recordId} by the record id(if there is one set) and the {connectedUserId} with the id of the connected user

**Comment by Sarveshgithub** [comment]
@mickaelgudin i have implemented the chanes

**Comment by mickaelgudin** [comment]
@Sarveshgithub thank you for the implementation.

I reviewed your changes, **you should use replaceAll and not replace in the js method appendWhere**, otherwise we cannot specify the recordId on multiple criterias, same goes for connectedUserId.

Can you implement this fix?
Thank you in advance.

**Comment by Sarveshgithub** [comment]
@mickaelgudin Agree, good catch, applied fix
