### ISSUE TITLE
Hyperlink to name field 

### ISSUE THREAD

**Issue by Sourabh42** [Sarveshgithub/sfdc-lwc-lightning-datatable#3]
Can u tell me how to create hyperlink to specific name column so when we click on name then it open in sub tab

**Comment by Sarveshgithub** [comment]
You can use url type in datatable, see that document : https://developer.salesforce.com/docs/component-library/bundle/lightning-datatable/documentation

Example
https://www.salesforcepoint.com/2020/06/how-to-add-hyper-link-for-name-column.html
