### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by mickaelgudin** [Sarveshgithub/sfdc-lwc-lightning-datatable#30]
The idea would be to provide a search bar for the list(displayed on demand via a new design property).
The records would be retrieved using a SOSL query.

**Comment by Sarveshgithub** [comment]
can start once the R3 release completed

**Comment by Sarveshgithub** [comment]
@mickaelgudin here are approache to build this, this may help!
Approach :
- write SOSL for search, within  fields, that are available `fields`
- use `formatData()` fuction for formatted
- from apex return data in `List<Object>` so it's easy to use `formatData()` funtion
- add search input after title
<img width="1252" alt="Screenshot 2022-08-23 at 7 32 35 PM" src="https://user-images.githubusercontent.com/40709233/186180253-472a1b7d-9ad8-479c-996f-3ab86c46e679.png">
cheers!
