### ISSUE TITLE
Column filter

### ISSUE THREAD

**Issue by mickaelgudin** [Sarveshgithub/sfdc-lwc-lightning-datatable#32]
The idea is to provide filter on column values. Ideally it would be an icon on the column name.
The multi-column filter should be included (ex : contacts with name X and Account Y).
Should be displayed on demand only(via boolean design property)

**Comment by Sarveshgithub** [comment]
can start once the R3 release completed

**Comment by Sarveshgithub** [comment]
@mickaelgudin any luck on the approach

**Comment by mickaelgudin** [comment]
@Sarveshgithub I've been focusing on testing but I believe the standard lightning-datatable doesn't provide this,

I think a form with a select for the label + and an input for the value (there would be one by default but with a button to add another filter) could be implemented.

**Comment by Sarveshgithub** [comment]
@mickaelgudin hmm ok np, let me see an idea to take an approach

**Comment by Sarveshgithub** [comment]
## Approach
Iterate columns JSON, and create Input fields based on type key, so onkeyup of Input search will work.
### Two Options are Search  
- Client-side search ( Disadvantage - search will work only current set of records based on limit )
- Server-side search based on SOSL ( This is optimal solution ) 
### Search Conditions
- It should be AND condition with fields, Ex: `FirstName = 'tes' AND Email = 'abc@m.com' `
### UI Example
<img width="1230" alt="Screenshot 2022-09-15 at 12 21 18 PM" src="https://user-images.githubusercontent.com/40709233/190336118-bdf34208-b114-42e4-965f-0fb4f964eb65.png">

- Did Not work
lwc-datatable does not allow input tags in columns
first row of datatable as Input tag of table - can't possible

**Comment by mickaelgudin** [comment]
@Sarveshgithub 

The way to go is header level actions, here is an example for filter : https://www.thephani.com/lwc-lightning-datatable-header-level-actions/

**Comment by Sarveshgithub** [comment]
@mickaelgudin I am moving this to a new feature https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/issues/121 much more helpful and effective
