### ISSUE TITLE
columns : link declaration

### ISSUE THREAD

**Issue by mickaelgudin** [Sarveshgithub/sfdc-lwc-lightning-datatable#44]
a new prop :

**example with Contact**

columns : `Name,AccountId`

new prop to declare link for columns : `Name=Id,AccountId=AccountId`

**Comment by mickaelgudin** [comment]
@Sarveshgithub could would assign me this issue unless you have implemented it

**Comment by Sarveshgithub** [comment]
@mickaelgudin Yhea this can also cover in the R3 release, I can assign you R4 release enhancements, that enhancement is standalone, but I would suggest you can implement it once I complete R3. cheers!
