### ISSUE TITLE
Make promotion of the repository

### ISSUE THREAD

**Issue by mickaelgudin** [Sarveshgithub/sfdc-lwc-lightning-datatable#48]
At the end of the milestone R3 or R4.
We should write an article on medium.com to promote this repo to the salesforce community.

A linkedin post with a link to the repository and the medium article could be great as well.

**Comment by Sarveshgithub** [comment]
Why not, For sure we need to promote this repo, as this is a good product that has tons of functionality and can be easily configured in many ways. People should consider this.

- Make a LinkedIn post ( i already did last year 😁. at that moment only a few functionalities was there )
- Medium - ahh need to write paragraphs.
-  Share with your co-workers
- A tweet can also help to promote
- Youtube Video can also help to promote

**Comment by mickaelgudin** [comment]
- I'll do it with a redirection to the medium article and github repository
- I already shared it with co-workers and used it on a few projects
- A youtube video can be a great think (maybe this will come after the medium article we'll see)

**Comment by Sarveshgithub** [comment]
that's great! home some projects should sponsor us 😀
