### ISSUE TITLE
@Sarveshgithub There appears to be an error when I only declare basic fields without the "Customized field JSON",

### ISSUE THREAD

**Issue by Sarveshgithub** [Sarveshgithub/sfdc-lwc-lightning-datatable#62]
@Sarveshgithub There appears to be an error when I only declare basic fields without the "Customized field JSON",

The error doesn't say much it only says that the component couldn't be displayed(translating since my org is in french).

Could you have a look?

![image](https://user-images.githubusercontent.com/39730173/188003530-94fc64c7-d35a-460e-88d7-7b28a254e0bf.png)

_Originally posted by @mickaelgudin in https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/issues/43#issuecomment-1234739371_

**Comment by Sarveshgithub** [comment]
@mickaelgudin Let me see

**Comment by Sarveshgithub** [comment]
@mickaelgudin I have fixed it, can you check now?

**Comment by Sarveshgithub** [comment]
@mickaelgudin , I have a test search with the below values, but it didn't work, can you please see what's the failure?
```
                cmp.title = "Contacts";
		cmp.fields = "FirstName";
		cmp.objectName = "Contact";
		cmp.limit = 5;
		cmp.isCounterDisplayed = true;
		cmp.actionButtons = '[{"name": "New","label": "New","variant": "neutral"}]';
		cmp.showCheckboxes = true;
		cmp.showViewAll = false;
		cmp.hasPagination = false;
		cmp.hasSearchBar = true;
```

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/40709233/188099707-8178ad6c-b7fe-49f8-847c-11d1bc40c782.png">

**Comment by mickaelgudin** [comment]
the error of "Customized field JSON" is still here (it appears when I don't use local config),

Can you check if the error appears when we use the app builder?


As for the error on the search bar, could you create an issue(bug) with your comment and screenshot?

**Comment by Sarveshgithub** [comment]
@mickaelgudin It's working at my end. not sure why it's not working for you. have taken the latest from `master`?
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/40709233/188124592-1d0767f6-d8a8-41d1-b42e-30cfaeda567c.png">

**Comment by Sarveshgithub** [comment]
[Ignore](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/issues/62#issuecomment-1235230664) this, My Bad it's working in Org.

**Comment by mickaelgudin** [comment]
@Sarveshgithub yeah my bad the new version is working, but there is an error when declaring a label override on a column

![image](https://user-images.githubusercontent.com/39730173/188192953-503e246e-9b3f-43ab-a9dd-a082d32d2197.png)

**Comment by Sarveshgithub** [comment]
@mickaelgudin I have checked, and it's working 
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/40709233/188307359-4bb1b6a0-f6c5-4163-ab40-c9528d84e9ad.png">

**Comment by mickaelgudin** [comment]
your're right it's working, the component shows error when we change the JSON we have to refresh the page and paste the JSON but it's working.

I made a PR to update the doc since the JSON contained formating error.
You can close this issue
